-- CreateTable
CREATE TABLE `Users` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `UIN` VARCHAR(191) NOT NULL,
    `SPRINGINFO` INTEGER NOT NULL DEFAULT 0,
    `BOBASOCIAL` INTEGER NOT NULL DEFAULT 0,
    `CHEVRONGBM` INTEGER NOT NULL DEFAULT 0,
    `COMSOC1` INTEGER NOT NULL DEFAULT 0,
    `COMSOC2` INTEGER NOT NULL DEFAULT 0,
    `COMSOC3` INTEGER NOT NULL DEFAULT 0,
    `COMSOC4` INTEGER NOT NULL DEFAULT 0,
    `COMSOC5` INTEGER NOT NULL DEFAULT 0,
    `DOWGBM` INTEGER NOT NULL DEFAULT 0,
    `ETAMGBM` INTEGER NOT NULL DEFAULT 0,
    `LAUNCHGBM` INTEGER NOT NULL DEFAULT 0,
    `LOCKHEEDGBM` INTEGER NOT NULL DEFAULT 0,
    `SQUADMIXER` INTEGER NOT NULL DEFAULT 0,
    `WILLIAMSGBM` INTEGER NOT NULL DEFAULT 0,
    `PEPSICOGBM` INTEGER NOT NULL DEFAULT 0,
    `GBM1` INTEGER NOT NULL DEFAULT 0,

    UNIQUE INDEX `Users_UIN_key`(`UIN`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `UIN` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `User_UIN_key`(`UIN`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Event` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(191) NOT NULL,
    `date` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Attendance` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `eventId` INTEGER NOT NULL,
    `attended` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
